### ISSUE TITLE
How to get an acc of 96.21 on PennAction?

### ISSUE THREAD

**Issue by mariolew** [frankchen121212/MobilePose-master#3]
I try to follow Fintune LPM on PennAction (init weight) and train the model. But I can only get 86% acc on PennAction.

**Comment by frankchen121212** [comment]
Sorry for the late reply, this repo hasn't been maintained for a long time. In the recurrent point of view, you could have 2 approaches:

1. Simply downloaded the official trained caffee model and transfer it into pytorch model and finetune it **only** on PennAction dataset. This will give you about 96.2% PCK0.2 on PennAction.

2. Follow the routine and train the model from LSP, MPII to PennAciton. This will give you about 95.7% PCK0.2 on PennAction dataset.

I used LMDB data format for PennAction dataset, so you may generate the dataset using the jupyter notebook script shared in the directory in /data/PennAction. Different dataset format may also affect the results.

Also, during evaluation, I do not consider those invisible joints and such consideration is included in the evaluation metrics. You may also want to double check that.

Because this was a recurrent work during my undergraduate study, this repo is no longer updated. You are also welcomed to query about some technical details through the email: siyuan.chen@kaust.edu.sa
